openapi: 3.0.3
info:
  title: andromeda
  description: |-
  version: 1.0.0
servers:
  - url: https://petstore3.swagger.io/api/v3
tags:
  - name: people porno
    description: estrella de cine porno
    externalDocs:
      description: Find out more
      url: http://swagger.io

paths:
  /peopleporn:
    get:
      tags:
        - people porno
      summary: Finds all person or by category
      description: return all person or all person of a category
      operationId: getAllPeopleporn
      parameters:
        - name: category
          in: query
          description: to filter all person of one category
          required: false
          explode: true
          schema:
            type: string
            default: mujer
            enum:
              - hombre
              - mujer
              - trava
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Peopleporn'
        '400':
          description: Invalid status value
  
    post:
      tags:
        - people porno
      summary: Add a new person
      description: Add a new person
      operationId: addPerson
      requestBody:
        description: Create a new person
        content:
          application/json:
            schema:
              required:
                - name
                - foto
                - fechaNacimiento
                - categoria
              type: object
              properties:
                name:
                  type: string
                  example: olivia
                fechaNacimiento:
                  type: string
                  example: "1985-02-23"
                foto:
                  type: string
                  example: www.google.com/fsdfvf
                categoria:
                  type: string
                  description: categoria que corresponde la persona
                  enum:
                    - hombre
                    - mujer
                    - trava
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Peopleporn'          
        '405':
          description: Invalid input
  /peoleporn/{id}:  
    get:
      tags:
        - people porno
      summary: Finds a person  by id
      description: return one person by id
      operationId: getAPersonporn
      parameters:
        - name: id
          in: path
          description: to find one person
          required: true
          explode: true
          schema:
            type: string
         
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Peopleporn'
        '400':
          description: Invalid status value
    put:
      tags:
        - people porno
      summary: Update an existing persona porno
      description: Update an existing persona porno by Id
      operationId: updatePet
      parameters:
        - name: id
          in: path
          description: to find one person
          required: true
          explode: true
          schema:
            type: string
      requestBody:
        description: Update an existent persona in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Peopleporn'
        required: true
      responses:
          default:
           description: successful operation
    delete:
      tags:
        - people porno
      summary: elimina an existing persona porno
      description: elimina an existing persona porno by Id
      operationId: delete
      parameters:
        - name: id
          in: path
          description: to find one person
          required: true
          explode: true
          schema:
            type: string
      responses:
          default:
           description: successful operation      
components:
  schemas:

    Peopleporn:
      required:
        - name
        - foto
        - fechaNacimiento
        - categoria
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: olivia
        fechaNacimiento:
          type: string
          example: "1985-02-23"
        foto:
          type: string
          example: www.google.com/fsdfvf
        categoria:
          type: string
          description: categoria que corresponde la persona
          enum:
            - hombre
            - mujer
            - trava
     
  